basePath: /v1
definitions:
  models.Member:
    properties:
      address1:
        type: string
      address2:
        type: string
      confirmation_time:
        type: string
      country_id:
        type: integer
      district_id:
        type: integer
      email:
        type: string
      id:
        type: integer
      notes:
        type: string
      organization:
        type: string
      passwd:
        type: string
      phone:
        type: string
      postal_code:
        type: string
      province_id:
        type: integer
      registration_time:
        type: string
      subdistrict_id:
        type: integer
      update_time:
        type: string
      username:
        type: string
    type: object
host: localhost:12345
info:
  contact:
    email: dev@biomassx.com
    name: BiomassX team
  description: An API for BiomassX
  title: BiomassX API
  version: "1.0"
paths:
  /v1/members/:
    post:
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Member'
      summary: Create a new member
      tags:
      - member
  /v1/members/{id}:
    delete:
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/models.Member'
      summary: Delete a member by ID
      tags:
      - member
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Member'
      summary: Get a member by ID
      tags:
      - member
    put:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Member'
      summary: Update a member by ID
      tags:
      - member
swagger: "2.0"
